# Generated by Django 3.0.7 on 2020-07-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubigeo',
            name='department',
            field=models.CharField(help_text='Departamento', max_length=64, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='ubigeo',
            name='district',
            field=models.CharField(help_text='Distrito', max_length=64, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='ubigeo',
            name='province',
            field=models.CharField(max_length=64, verbose_name='Province'),
        ),
    ]
