# Generated by Django 3.0.7 on 2020-07-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_address',
        ),
    ]
